project_id = "ycvfyorgkhuxcosfrsxs"

[functions.save-bet-to-history]
verify_jwt = false

[functions.save-parlay-to-history]
verify_jwt = false

[functions.get-bet-history]
verify_jwt = false

[functions.get-parlay-history]
verify_jwt = false

[functions.update-member-count]
verify_jwt = false